language: python
python:
  - "2.7"
  - "3.6"
install:
  - pip install git+git://github.com/Julian/jsonschema.git@v3.0.0a3#egg=jsonschema
  - wget -O draft7.json http://json-schema.org/draft-07/schema
script:
  - jsonschema -i src/animal_models.json draft7.json
  - jsonschema -i src/drug.json draft7.json
  - jsonschema -i src/expression.json draft7.json
  - jsonschema -i src/genetics.json draft7.json
  - jsonschema -i src/literature_curated.json draft7.json
  - jsonschema -i src/literature_mining.json draft7.json
