language: python
python:
  - "2.7"
  - "3.6"
install:
  - pip install git+git://github.com/Julian/jsonschema.git@v3.0.0a3#egg=jsonschema
  - wget -O draft7.json http://json-schema.org/draft-07/schema
script:
  - find src -name "*.json" -exec jsonschema -i {} draft7.json \;
